### ISSUE TITLE
require not defined in index.html

### ISSUE THREAD

**Issue by SantoshSrinivas79** [jcblw/electron-test-app#1]
Hi,

I just started looking at electron and came across this test repo.

I am getting the following error when I run your project

``` sh
[34442:0425/230606:INFO:CONSOLE(9)] "Uncaught ReferenceError: require is not defined", source: file:///Users/s/temp/electron/electron-test-app/app/index.html (9)
```

The error is related to the below code in `index.html`.

``` js
  <script>
    //monkey patch in client
    require('./client');
  </script>
```

Any idea on how to solve it? Sorry, this may be VERY basic.

**Comment by jcblw** [comment]
hmmm, are you running that file outside of the electron app. `require` should be available from there.

**Comment by SantoshSrinivas79** [comment]
Ok. I got this running. I used `npm start` per your docs but when I use `electron app` instead, I am able to make it work.

**Comment by jcblw** [comment]
`npm start` should work as well. since that does the same thing with having to download electron globally.

https://github.com/jcblw/electron-test-app/blob/master/package.json#L7

did you get any errors installing, or running `npm start`

**Comment by SantoshSrinivas79** [comment]
This is my entire output. No idea why the problem is occuring

``` sh
➜ electron-test-app git:(master) ✗ npm start

> test-electron-app@1.0.0 start /Users/s/temp/electron/electron-test-app
> electron app/

[37247:0426/073824:INFO:renderer_main.cc(212)] Renderer process started
[37245:0426/073824:INFO:CONSOLE(9)] "Uncaught ReferenceError: require is not defined", source: file:///Users/santoshsrinivas/temp/electron/electron-test-app/app/index.html (9)
```

**Comment by jcblw** [comment]
yeah that is weird sorry bout that.

**Comment by jcblw** [comment]
do you have some typeof symlinking going on? on of the path is `s` vs your name. Im wondering if that has anything to do with it.

**Comment by sathiraumesh** [comment]
Enable node integration when creating the window

```
app.on('ready', () => {
    console.log('Hello from Electron.');
    mainWindow = new BrowserWindow({webPreferences: {
        nodeIntegration: true
      }});
    mainWindow.webContents.loadFile(path.join(__dirname,"index.html"));
    mainWindow.webContents.openDevTools();
});

```

**Comment by arcsoftkamal** [comment]
after set  nodeIntegration: true I am still getting same error
